FROM --platform=linux/arm64 busybox:1.34.1 as source
FROM --platform=linux/arm64 gcr.io/distroless/base-debian11

COPY --from=source /bin/sh /bin/sh
COPY --from=source /bin/mkdir /bin/mkdir

ADD /raft-linux-arm64 /usr/local/bin/

CMD ["/usr/local/bin/raft-linux-arm64"]
ENTRYPOINT ["/usr/local/bin/raft-linux-arm64"]